[formatter.typos]
command = "typos"
includes = ["*.md", "*.ts", "*.nix"]
options = ["--write-changes"]
priority = 0                         # typos should run first

[formatter.typescript]
command = "biome"
options = ["format", "--write"]
includes = ["*.ts"]

[formatter.md]
command = "mdformat"
includes = ["*.md"]
excludes = ["LICENSE.md"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml", "*.editorconfig"]
